[lumberjacks]
    [lumberjacks.default]
        max_size = 128
        max_backups = 100
        max_age = 31
        compress = false

    [lumberjacks.debug]
        max_size = 128
        max_backups = 100
        max_age = 31
        compress = false

    [lumberjacks.info]
        max_size = 128
        max_backups = 100
        max_age = 31
        compress = false

    [lumberjacks.warn]
        max_size = 128
        max_backups = 100
        max_age = 31
        compress = false

    [lumberjacks.error]
        max_size = 128
        max_backups = 100
        max_age = 365
        compress = false